/**
 * Flashcard Parser Service
 * Handles parsing and extracting flashcards from markdown content
 *
 * Supports multi-line questions including code blocks:
 * ```
 * Question text
 * ```typescript
 * code example
 * ``` #flashcard
 * Answer text
 * ```
 *
 * Also supports:
 * - Cloze deletions: {{c1::text}} and {{c1::text::hint}}
 * - Reversed cards via #flashcard-reverse tag
 */

import {
	hasClozeContent,
	parseClozeTemplate,
} from "@features/study/services/flashcard/cloze-parser.service";
import { FLASHCARD_CONFIG } from "@shared/constants";
import type { FlashcardItem } from "@shared/types";

export class FlashcardParserService {
	private codeBlockPattern: RegExp = /^\s*(```|~~~)/;
	private tagPattern: RegExp;
	private sourceCommentPattern: RegExp = /^<!--\s*source:\s*(.*?)\s*-->$/;

	constructor() {
		// Matches line ending with #flashcard-reverse or #flashcard
		// Captures: [1] text before tag, [2] the matched tag
		this.tagPattern = new RegExp(
			`^(.*)\\s*(${FLASHCARD_CONFIG.reverseTag}|${FLASHCARD_CONFIG.tag})\\s*$`,
		);
	}

	/**
	 * Extract flashcards from content
	 * Parses markdown content and returns all flashcard items with their metadata
	 * Each card gets a new UUID generated by crypto.randomUUID()
	 *
	 * Supports multi-line questions including code blocks.
	 * Questions are accumulated until #flashcard tag is found.
	 * Empty lines (outside code blocks) reset the question accumulation.
	 */
	extractFlashcards(content: string): FlashcardItem[] {
		const flashcards: FlashcardItem[] = [];
		const lines = content.split("\n");

		let questionLines: string[] = [];
		let inQuestionCodeBlock = false;

		for (let i = 0; i < lines.length; i++) {
			const line = lines[i] ?? "";
			const trimmedLine = line.trim();

			// Toggle code block state for question accumulation
			if (this.codeBlockPattern.test(line)) {
				inQuestionCodeBlock = !inQuestionCodeBlock;
			}

			const tagMatch = line.match(this.tagPattern);

			if (tagMatch) {
				// Found #flashcard or #flashcard-reverse
				const beforeTag = tagMatch[1] ?? "";
				const matchedTag = tagMatch[2] ?? "";

				// Add the part before tag to question lines
				questionLines.push(beforeTag);

				const question = questionLines.join("\n").trim();
				questionLines = [];
				inQuestionCodeBlock = false;

				if (!question) {
					continue; // Skip if no question content
				}

				const isReverse = matchedTag === FLASHCARD_CONFIG.reverseTag;

				// Collect answer
				const answerLines: string[] = [];
				let inAnswerCodeBlock = false;

				i++;
				// Skip leading empty lines between question and answer
				while (i < lines.length && (lines[i] ?? "").trim() === "") {
					i++;
				}

				while (i < lines.length) {
					const answerLine = lines[i] ?? "";

					// Skip legacy ID lines
					if (/^ID:\s*\d+/.test(answerLine)) {
						i++;
						continue;
					}

					// Toggle code block state for answer
					if (this.codeBlockPattern.test(answerLine)) {
						inAnswerCodeBlock = !inAnswerCodeBlock;
					}

					// Check for end of answer:
					// - Empty line outside code block
					// - Next #flashcard tag
					if (
						(answerLine.trim() === "" && !inAnswerCodeBlock) ||
						this.tagPattern.test(answerLine)
					) {
						i--;
						break;
					}

					answerLines.push(answerLine);
					i++;
				}

				// Extract <!-- source: ... --> from answer lines (scan backward)
				let sourceText: string | undefined;
				for (let j = answerLines.length - 1; j >= 0; j--) {
					const sourceMatch = answerLines[j]
						?.trim()
						.match(this.sourceCommentPattern);
					if (sourceMatch) {
						sourceText = sourceMatch[1]?.trim() || undefined;
						answerLines.splice(j, 1);
						break;
					}
				}

				const answer = answerLines.join("\n").trim();

				// Handle cloze syntax
				if (hasClozeContent(question)) {
					const clozeCards = parseClozeTemplate(question);
					for (const cloze of clozeCards) {
						const fullAnswer = answer
							? `${cloze.answer}\n\n${answer}`
							: cloze.answer;
						flashcards.push({
							question: cloze.question,
							answer: fullAnswer,
							id: crypto.randomUUID(),
							cardType: "cloze",
							clozeTemplate: question,
							clozeIndex: cloze.clozeIndex,
							sourceText,
						});
					}
				} else {
					// Basic card
					const basicId = crypto.randomUUID();
					flashcards.push({
						question,
						answer,
						id: basicId,
						sourceText,
					});

					// If #flashcard-reverse, also generate a reversed card
					if (isReverse && answer) {
						flashcards.push({
							question: answer,
							answer: question,
							id: crypto.randomUUID(),
							cardType: "reversed",
							reverseOfBatchId: basicId,
							sourceText,
						});
					}
				}
			} else if (trimmedLine === "" && !inQuestionCodeBlock) {
				// Empty line outside code block - reset question accumulation
				questionLines = [];
			} else {
				// Accumulate line as potential question content
				questionLines.push(line);
			}
		}

		return flashcards;
	}

	/**
	 * Check if a line is a flashcard question line (contains #flashcard tag)
	 */
	isFlashcardLine(line: string): boolean {
		return this.tagPattern.test(line);
	}

	/**
	 * Get the flashcard tag pattern for external use
	 */
	getFlashcardTag(): string {
		return FLASHCARD_CONFIG.tag;
	}
}
