import {
	copyFileSync,
	readFileSync,
	writeFileSync,
	realpathSync,
	existsSync,
	mkdirSync,
	watch,
} from "fs";
import { join, resolve } from "path";
import { execSync, spawn } from "child_process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN
if you want to view the source, please visit the github repository of this plugin
*/
`;

// "production" = minified, no sourcemaps
// "once"       = dev build, single run (used by watch subprocess)
// undefined    = dev build + watch mode
const mode = process.argv[2] as "production" | "once" | undefined;
const prod = mode === "production";

const PLUGIN_ID = "true-recall";
const VAULT_PATH = process.env.VAULT;

const projectOutfile = "main.js";
const vaultPluginDir = VAULT_PATH
	? join(VAULT_PATH, ".obsidian", "plugins", PLUGIN_ID)
	: null;

if (vaultPluginDir && !existsSync(vaultPluginDir)) {
	mkdirSync(vaultPluginDir, { recursive: true });
}

// When vault dir is symlinked to project root, copying files to vault
// is a no-op (they're already in the right place). Detect this to avoid
// copyFileSync destroying the source when src and dst resolve to the same file.
const vaultIsProjectRoot =
	vaultPluginDir != null &&
	realpathSync(vaultPluginDir) === realpathSync(".");

function buildCSS(): void {
	try {
		const minifyFlag = prod ? " --minify" : "";
		execSync(
			`bunx @tailwindcss/cli -i src/shared/ui/styles.css -o styles.css${minifyFlag}`,
			{ stdio: "pipe" },
		);
		console.log(
			`\u2713 CSS built with Tailwind CLI${prod ? " (minified)" : ""}`,
		);
	} catch (err: unknown) {
		const message = err instanceof Error ? err.message : String(err);
		console.error("CSS build failed:", message);
		throw err;
	}
}

function safeCopy(src: string, dst: string): void {
	const absSrc = resolve(src);
	const absDst = resolve(dst);
	if (absSrc === absDst) return;

	try {
		const realSrc = realpathSync(absSrc);
		const realDst = realpathSync(absDst);
		if (realSrc === realDst) return;
	} catch {
		// Destination may not exist yet — proceed with copy
	}

	copyFileSync(src, dst);
}

function copyToVault(): void {
	if (!vaultPluginDir) return;
	if (vaultIsProjectRoot) {
		if (!prod) {
			writeFileSync(join(vaultPluginDir, ".hotreload"), "");
		}
		return;
	}

	try {
		safeCopy(projectOutfile, join(vaultPluginDir, "main.js"));

		if (existsSync("manifest.json")) {
			safeCopy("manifest.json", join(vaultPluginDir, "manifest.json"));
		}
		if (existsSync("styles.css")) {
			safeCopy("styles.css", join(vaultPluginDir, "styles.css"));
		}

		const sqljsWasm = "node_modules/sql.js/dist/sql-wasm.wasm";
		if (existsSync(sqljsWasm)) {
			safeCopy(sqljsWasm, join(vaultPluginDir, "sql-wasm.wasm"));
		}

		if (!prod) {
			writeFileSync(join(vaultPluginDir, ".hotreload"), "");
		}

		console.log(`\u2713 Copied to vault: ${vaultPluginDir}`);
	} catch (err: unknown) {
		const message = err instanceof Error ? err.message : String(err);
		console.error("Failed to copy to vault:", message);
	}
}

async function build(): Promise<boolean> {
	buildCSS();

	const result = await Bun.build({
		entrypoints: ["src/main.ts"],
		outdir: ".",
		naming: "[name].[ext]",
		format: "cjs",
		target: "node",
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/*",
			"@lezer/*",
		],
		define: {
			"process.env.SUPABASE_URL": JSON.stringify(
				process.env.SUPABASE_URL || "",
			),
			"process.env.SUPABASE_ANON_KEY": JSON.stringify(
				process.env.SUPABASE_ANON_KEY || "",
			),
			"process.env.POWERSYNC_URL": JSON.stringify(
				process.env.POWERSYNC_URL || "",
			),
		},
		loader: { ".wasm": "file" },
		minify: prod,
		sourcemap: prod ? "none" : "inline",
	});

	if (!result.success) {
		console.error("Build failed:");
		for (const log of result.logs) {
			console.error(" ", log.message);
		}
		return false;
	}

	// Bun.build has no banner option — prepend manually
	const content = readFileSync(projectOutfile, "utf8");
	writeFileSync(projectOutfile, banner + content);

	copyToVault();
	return true;
}

if (mode === "production" || mode === "once") {
	// Single build (production or subprocess dev rebuild)
	const ok = await build();
	process.exit(ok ? 0 : 1);
} else {
	// Dev watch mode: initial build + watcher
	const ok = await build();
	if (!ok) {
		console.error("Initial build failed, exiting.");
		process.exit(1);
	}
	console.log("[watch] watching for changes...");

	// Bun.build() can only be called once per process reliably (Bun v1.3.4 bug).
	// Spawn a subprocess for each rebuild to work around this.
	let debounceTimer: ReturnType<typeof setTimeout> | null = null;
	let rebuilding = false;

	watch("src", { recursive: true }, (_event, filename) => {
		if (debounceTimer) clearTimeout(debounceTimer);
		debounceTimer = setTimeout(async () => {
			if (rebuilding) return;
			rebuilding = true;
			console.log(`[watch] rebuilding (${String(filename)} changed)...`);
			const proc = Bun.spawn(["bun", "build.ts", "once"], {
				stdout: "inherit",
				stderr: "inherit",
			});
			const code = await proc.exited;
			if (code === 0) {
				console.log("[watch] build finished");
			} else {
				console.error(`[watch] build failed (exit ${code})`);
			}
			rebuilding = false;
		}, 150);
	});

	// Watch CSS separately — Bun.build doesn't track non-bundled files
	const cssWatcher = spawn(
		"bunx",
		[
			"@tailwindcss/cli",
			"-i",
			"src/shared/ui/styles.css",
			"-o",
			"styles.css",
			"--watch",
		],
		{ stdio: "inherit" },
	);
	cssWatcher.on("error", (err) =>
		console.error("CSS watcher error:", err.message),
	);

	// Copy styles.css to vault whenever Tailwind rebuilds it
	if (vaultPluginDir && !vaultIsProjectRoot) {
		watch("styles.css", () => {
			try {
				safeCopy("styles.css", join(vaultPluginDir, "styles.css"));
			} catch {
				// File may not exist yet on first watch event
			}
		});
	}

	const cleanup = () => {
		cssWatcher.kill();
		process.exit(0);
	};
	process.on("SIGINT", cleanup);
	process.on("SIGTERM", cleanup);
}
