import 'dotenv/config';
import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, writeFileSync, existsSync, mkdirSync, readFileSync } from "fs";
import { join } from "path";
import { execSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const PLUGIN_ID = "episteme";
const VAULT_PATH = process.env.VAULT;

// Determine output paths
const projectOutfile = "main.js";
const vaultPluginDir = VAULT_PATH
	? join(VAULT_PATH, ".obsidian", "plugins", PLUGIN_ID)
	: null;

// Ensure vault plugin directory exists
if (vaultPluginDir && !existsSync(vaultPluginDir)) {
	mkdirSync(vaultPluginDir, { recursive: true });
}

// Legacy CSS files (kept during migration, will be removed progressively)
const legacyCssFiles = [
	"src/ui/settings/styles.css",
	"src/ui/components/styles.css",
	"src/ui/panel/styles.css",
	"src/ui/review/styles.css",
	"src/ui/modals/styles.css",
	"src/ui/session/styles.css",
	"src/ui/stats/styles.css",
	"src/ui/projects/styles.css",
	"src/ui/browser/styles.css",
	"src/ui/mobile.css",
];

// Process CSS with PostCSS (Tailwind v4)
function buildCSS() {
	try {
		// Step 1: Process Tailwind CSS with PostCSS
		execSync('npx postcss src/ui/styles.css -o styles.tailwind.css', { stdio: 'pipe' });

		// Step 2: Concatenate legacy CSS files (during migration period)
		let legacyCSS = "";
		legacyCssFiles.forEach(file => {
			if (existsSync(file)) {
				const content = readFileSync(file, "utf-8");
				legacyCSS += content + "\n\n";
			}
		});

		// Step 3: Combine Tailwind output with legacy CSS
		const tailwindCSS = existsSync("styles.tailwind.css")
			? readFileSync("styles.tailwind.css", "utf-8")
			: "";

		// Tailwind first (base/utilities), then legacy overrides
		writeFileSync("styles.css", tailwindCSS + "\n\n/* Legacy CSS (will be removed after migration) */\n\n" + legacyCSS, "utf-8");

		console.log("✓ CSS processed with PostCSS (Tailwind + legacy)");
	} catch (err) {
		console.error("PostCSS build failed:", err.message);
		// Fallback to legacy concatenation if PostCSS fails
		let combinedCSS = "";
		legacyCssFiles.forEach(file => {
			if (existsSync(file)) {
				const content = readFileSync(file, "utf-8");
				combinedCSS += content + "\n\n";
			}
		});
		writeFileSync("styles.css", combinedCSS, "utf-8");
		console.log("⚠ Fallback: CSS concatenated without Tailwind");
	}
}

// Copy static files to vault
function copyToVault() {
	if (!vaultPluginDir) return;

	try {
		// Copy main.js
		copyFileSync(projectOutfile, join(vaultPluginDir, "main.js"));

		// Copy manifest.json and styles.css if they exist
		if (existsSync("manifest.json")) {
			copyFileSync("manifest.json", join(vaultPluginDir, "manifest.json"));
		}
		if (existsSync("styles.css")) {
			copyFileSync("styles.css", join(vaultPluginDir, "styles.css"));
		}

		// Copy sql.js WASM
		const sqljsWasm = "node_modules/sql.js/dist/sql-wasm.wasm";
		if (existsSync(sqljsWasm)) {
			copyFileSync(sqljsWasm, join(vaultPluginDir, "sql-wasm.wasm"));
			console.log("✓ Copied sql-wasm.wasm");
		}

		// Note: wa-sqlite WASM is now bundled directly via esbuild's binary loader

		// Create .hotreload file for hot-reload plugin
		if (!prod) {
			writeFileSync(join(vaultPluginDir, ".hotreload"), "");
		}

		console.log(`✓ Copied to vault: ${vaultPluginDir}`);
	} catch (err) {
		console.error("Failed to copy to vault:", err.message);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	define: {
		'process.env.SUPABASE_URL': JSON.stringify(process.env.SUPABASE_URL || ''),
		'process.env.SUPABASE_ANON_KEY': JSON.stringify(process.env.SUPABASE_ANON_KEY || ''),
		'process.env.POWERSYNC_URL': JSON.stringify(process.env.POWERSYNC_URL || ''),
	},
	loader: {
		// Bundle WASM as binary data to avoid fetch issues in Electron
		'.wasm': 'binary',
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: projectOutfile,
	minify: prod,
	plugins: [{
		name: "copy-to-vault",
		setup(build) {
			build.onStart(() => {
				buildCSS(); // Process CSS with PostCSS (Tailwind + legacy)
			});
			build.onEnd(() => {
				copyToVault();
			});
		}
	}],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
