import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, writeFileSync, existsSync, mkdirSync, readFileSync } from "fs";
import { join } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const PLUGIN_ID = "episteme";
const VAULT_PATH = process.env.VAULT;

// Determine output paths
const projectOutfile = "main.js";
const vaultPluginDir = VAULT_PATH
	? join(VAULT_PATH, ".obsidian", "plugins", PLUGIN_ID)
	: null;

// Ensure vault plugin directory exists
if (vaultPluginDir && !existsSync(vaultPluginDir)) {
	mkdirSync(vaultPluginDir, { recursive: true });
}

// CSS files to concatenate (in correct order)
const cssFiles = [
	"src/ui/settings/styles.css",
	"src/ui/components/styles.css",
	"src/ui/panel/styles.css",
	"src/ui/review/styles.css",
	"src/ui/modals/styles.css",
	"src/ui/stats/styles.css",
	"src/ui/projects/styles.css",
	"src/ui/browser/styles.css",
	"src/ui/mobile.css",
];

// Combine CSS files into single styles.css
function combineCSS() {
	let combinedCSS = "";
	cssFiles.forEach(file => {
		if (existsSync(file)) {
			const content = readFileSync(file, "utf-8");
			combinedCSS += content + "\n\n";
		}
	});
	writeFileSync("styles.css", combinedCSS, "utf-8");
	console.log("✓ CSS combined into styles.css");
}

// Copy static files to vault
function copyToVault() {
	if (!vaultPluginDir) return;

	try {
		// Copy main.js
		copyFileSync(projectOutfile, join(vaultPluginDir, "main.js"));

		// Copy manifest.json and styles.css if they exist
		if (existsSync("manifest.json")) {
			copyFileSync("manifest.json", join(vaultPluginDir, "manifest.json"));
		}
		if (existsSync("styles.css")) {
			copyFileSync("styles.css", join(vaultPluginDir, "styles.css"));
		}

		// Copy CR-SQLite WASM file
		const crsqliteWasm = "node_modules/@vlcn.io/crsqlite-wasm/dist/crsqlite.wasm";
		if (existsSync(crsqliteWasm)) {
			copyFileSync(crsqliteWasm, join(vaultPluginDir, "crsqlite.wasm"));
			console.log("✓ Copied crsqlite.wasm");
		}

		// Copy sql.js WASM as fallback
		const sqljsWasm = "node_modules/sql.js/dist/sql-wasm.wasm";
		if (existsSync(sqljsWasm)) {
			copyFileSync(sqljsWasm, join(vaultPluginDir, "sql-wasm.wasm"));
			console.log("✓ Copied sql-wasm.wasm");
		}

		// Create .hotreload file for hot-reload plugin
		if (!prod) {
			writeFileSync(join(vaultPluginDir, ".hotreload"), "");
		}

		console.log(`✓ Copied to vault: ${vaultPluginDir}`);
	} catch (err) {
		console.error("Failed to copy to vault:", err.message);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: projectOutfile,
	minify: prod,
	plugins: [{
		name: "copy-to-vault",
		setup(build) {
			build.onStart(() => {
				combineCSS(); // Combine CSS files before building
			});
			build.onEnd(() => {
				copyToVault();
			});
		}
	}],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
