import esbuild from "esbuild";
import { builtinModules } from "node:module";
import {
	copyFileSync,
	existsSync,
	mkdirSync,
	realpathSync,
	watch,
	writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { execSync, spawn } from "node:child_process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";
const PLUGIN_ID = "true-recall";
const VAULT_PATH = process.env.VAULT;

const projectOutfile = "main.js";
const vaultPluginDir = VAULT_PATH
	? join(VAULT_PATH, ".obsidian", "plugins", PLUGIN_ID)
	: null;

if (vaultPluginDir && !existsSync(vaultPluginDir)) {
	mkdirSync(vaultPluginDir, { recursive: true });
}

// When vault dir is symlinked to project root, copying files to vault
// is a no-op (they're already in the right place). Detect this to avoid
// copyFileSync destroying the source when src and dst resolve to the same file.
const vaultIsProjectRoot =
	vaultPluginDir != null &&
	realpathSync(vaultPluginDir) === realpathSync(".");

function safeCopy(src, dst) {
	const absSrc = resolve(src);
	const absDst = resolve(dst);
	if (absSrc === absDst) return;
	try {
		if (realpathSync(absSrc) === realpathSync(absDst)) return;
	} catch {
		// Destination may not exist yet — proceed with copy
	}
	copyFileSync(src, dst);
}

function buildCSS() {
	try {
		const minifyFlag = prod ? " --minify" : "";
		execSync(
			`bunx @tailwindcss/cli -i packages/obsidian/src/styles.css -o styles.css${minifyFlag}`,
			{ stdio: "pipe" },
		);
		console.log(`\u2713 CSS built${prod ? " (minified)" : ""}`);
	} catch (err) {
		console.error("CSS build failed:", err.message);
		throw err;
	}
}

function copyToVault() {
	if (!vaultPluginDir) return;
	if (vaultIsProjectRoot) {
		if (!prod) writeFileSync(join(vaultPluginDir, ".hotreload"), "");
		// Keep sqlite3.wasm up-to-date in the project root (vault = project root setup)
		const wasmSrc = "node_modules/@sqlite.org/sqlite-wasm/dist/sqlite3.wasm";
		if (existsSync(wasmSrc)) safeCopy(wasmSrc, "sqlite3.wasm");
		return;
	}

	try {
		safeCopy(projectOutfile, join(vaultPluginDir, "main.js"));

		if (existsSync("manifest.json"))
			safeCopy("manifest.json", join(vaultPluginDir, "manifest.json"));
		if (existsSync("styles.css"))
			safeCopy("styles.css", join(vaultPluginDir, "styles.css"));

		const wasm = "node_modules/@sqlite.org/sqlite-wasm/dist/sqlite3.wasm";
		if (existsSync(wasm))
			safeCopy(wasm, join(vaultPluginDir, "sqlite3.wasm"));

		if (!prod) writeFileSync(join(vaultPluginDir, ".hotreload"), "");
		console.log(`\u2713 Copied to vault: ${vaultPluginDir}`);
	} catch (err) {
		console.error("Failed to copy to vault:", err.message);
	}
}

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["packages/obsidian/src/main.ts"],
	bundle: true,
	metafile: true,
	alias: {
		"@true-recall/core": resolve("packages/core/src"),
		"@true-recall/obsidian": resolve("packages/obsidian/src"),
		"@true-recall/plugins": resolve("packages/plugins/src"),
		// downshift imports from 'react' — redirect to preact/compat
		react: "preact/compat",
		"react-dom": "preact/compat",
	},
	define: {},
	loader: { ".wasm": "binary" },
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	jsx: "automatic",
	jsxImportSource: "preact",
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: projectOutfile,
	minify: prod,
	plugins: [
		{
			name: "build-hooks",
			setup(build) {
				build.onEnd((result) => {
					if (result.errors.length === 0) copyToVault();
				});
			},
		},
	],
});

if (prod) {
	buildCSS();
	const result = await context.rebuild();
	if (result.metafile) {
		writeFileSync("meta.json", JSON.stringify(result.metafile));
	}
	process.exit(0);
} else {
	buildCSS();
	await context.watch();

	// Tailwind --watch for CSS hot reload
	const cssWatcher = spawn(
		"bunx",
		[
			"@tailwindcss/cli",
			"-i",
			"packages/obsidian/src/styles.css",
			"-o",
			"styles.css",
			"--watch",
		],
		{ stdio: "inherit" },
	);
	cssWatcher.on("error", (err) =>
		console.error("CSS watcher error:", err.message),
	);

	// Copy styles.css to vault whenever Tailwind rebuilds it
	if (vaultPluginDir && !vaultIsProjectRoot) {
		watch("styles.css", () => {
			try {
				safeCopy("styles.css", join(vaultPluginDir, "styles.css"));
			} catch {
				// File may not exist yet on first watch event
			}
		});
	}

	const cleanup = () => {
		cssWatcher.kill();
		process.exit(0);
	};
	process.on("SIGINT", cleanup);
	process.on("SIGTERM", cleanup);
}
