/**
 * Workload Forecast Calculator
 *
 * Predicts future review workload based on current card scheduling.
 */

import { State } from "ts-fsrs";

import { isLearningState } from "../../../helpers/card-state";
import type { FSRSCardData } from "../../../types";
import { formatLocalDate, startOfLocalDay } from "../../../utils";

/**
 * Minimal card source the forecast needs.
 *
 * Narrower than SqliteStoreService so the calculator stays testable without a
 * database.
 */
export interface WorkloadForecastCardStore {
	getCards(): FSRSCardData[];
}

/**
 * Sort a date→breakdown map into forecast entries, computing dueCount
 * and a running cumulative total in chronological order.
 */
export function toEntries(
	byDate: Map<string, WorkloadBreakdown>,
): WorkloadForecastEntry[] {
	const sorted = Array.from(byDate.entries()).sort((a, b) =>
		a[0].localeCompare(b[0]),
	);

	let cumulative = 0;
	return sorted.map(([date, breakdown]) => {
		const dueCount =
			breakdown.young +
			breakdown.mature +
			breakdown.learning +
			breakdown.projectedRelearning;
		cumulative += dueCount;
		return { date, dueCount, cumulative, breakdown };
	});
}

/** Review-card maturity threshold in days (matches MaturityCalculator). */
export const MATURE_INTERVAL_DAYS = 21;

/**
 * Expected relearning reviews generated by lapses among the review cards due
 * on a single day.
 *
 * Only review cards feed the estimate — counting learning cards here would
 * project relapses of cards that are already in the relearning population.
 */
export function projectRelearning(
	breakdown: Pick<WorkloadBreakdown, "young" | "mature">,
	requestRetention: number,
): number {
	const lapseRate = 1 - requestRetention;
	if (lapseRate <= 0) return 0;
	return Math.round((breakdown.young + breakdown.mature) * lapseRate);
}

/**
 * Decide whether a card counts toward the forecast at all.
 * Overdue cards stay eligible — see buildForecastEntries.
 */
function isForecastEligible(
	card: FSRSCardData,
	now: Date,
	endDate: Date,
): boolean {
	if (card.suspended) return false;
	if (card.buriedUntil && new Date(card.buriedUntil) > now) return false;
	return new Date(card.due) <= endDate;
}

/**
 * Build forecast entries from a card list.
 *
 * Shared by WorkloadForecastCalculator.getForecast() and the preset-filtered
 * variant so the bucketing rules cannot drift apart.
 *
 * @param requestRetention - When provided, adds projected relearning volume to
 * each day. Omit to report only cards that are actually scheduled.
 */
export function buildForecastEntries(
	cards: FSRSCardData[],
	days: number = 30,
	requestRetention?: number,
): WorkloadForecastEntry[] {
	const now = new Date();
	const todayStart = startOfLocalDay(now);
	const endDate = new Date(todayStart);
	endDate.setDate(endDate.getDate() + days);

	const forecast = new Map<string, WorkloadBreakdown>();
	const currentDate = new Date(todayStart);
	while (currentDate <= endDate) {
		forecast.set(formatLocalDate(currentDate), {
			young: 0,
			mature: 0,
			learning: 0,
			projectedRelearning: 0,
		});
		currentDate.setDate(currentDate.getDate() + 1);
	}

	for (const card of cards) {
		if (!isForecastEligible(card, now, endDate)) continue;

		// Overdue work is still work: anything due before today lands in today's
		// bucket. Learning cards use sub-day steps and are almost always slightly
		// past due, so a lower bound on `due` would drop them entirely.
		const due = new Date(card.due);
		const bucket = forecast.get(
			formatLocalDate(due < todayStart ? todayStart : due),
		);
		if (!bucket) continue;

		if (card.state === State.Review) {
			if (card.scheduledDays < MATURE_INTERVAL_DAYS) bucket.young++;
			else bucket.mature++;
		} else if (isLearningState(card.state)) {
			bucket.learning++;
		}
	}

	if (requestRetention !== undefined) {
		for (const bucket of forecast.values()) {
			bucket.projectedRelearning = projectRelearning(bucket, requestRetention);
		}
	}

	return toEntries(forecast);
}

/**
 * Daily workload forecast entry
 */
export interface WorkloadForecastEntry {
	/** Date (ISO date string) */
	date: string;
	/** Number of reviews due */
	dueCount: number;
	/** Running total of dueCount up to and including this date */
	cumulative: number;
	/** Breakdown by card maturity */
	breakdown: WorkloadBreakdown;
}

/**
 * Per-day workload composition.
 *
 * The first three fields count cards that are actually scheduled;
 * projectedRelearning is an estimate, not a card count.
 */
export interface WorkloadBreakdown {
	/** Review cards with interval < 21 days */
	young: number;
	/** Review cards with interval >= 21 days */
	mature: number;
	/** Cards in Learning/Relearning state */
	learning: number;
	/** Estimated extra reviews from lapses on this day (0 when not projected) */
	projectedRelearning: number;
}

/**
 * Workload forecast summary
 */
export interface WorkloadForecastSummary {
	/** Average daily workload */
	avgDaily: number;
	/** Peak day */
	peakDay: { date: string; count: number };
	/** Minimum day */
	minDay: { date: string; count: number };
	/** Days above target */
	daysAboveTarget: number;
	/** Recommended balance */
	needsBalancing: boolean;
}

/**
 * Workload Forecast Calculator
 *
 * Analyzes scheduled cards to predict future workload,
 * helping users plan their study time.
 */
export class WorkloadForecastCalculator {
	constructor(private cardStore: WorkloadForecastCardStore) {}

	/**
	 * Get workload forecast for the next N days
	 */
	getForecast(
		days: number = 30,
		excludeSourceUids?: ReadonlySet<string>,
		includeSourceUids?: ReadonlySet<string>,
		requestRetention?: number,
	): WorkloadForecastEntry[] {
		const cards = this.cardStore
			.getCards()
			.filter(
				(c) =>
					(!excludeSourceUids || !excludeSourceUids.has(c.sourceUid ?? "")) &&
					(!includeSourceUids || includeSourceUids.has(c.sourceUid ?? "")),
			);

		return buildForecastEntries(cards, days, requestRetention);
	}

	/**
	 * Get summary statistics for the forecast
	 */
	getSummary(
		targetPerDay: number,
		days: number = 30,
		excludeSourceUids?: ReadonlySet<string>,
		maxDeviation: number = 20,
		includeSourceUids?: ReadonlySet<string>,
		requestRetention?: number,
	): WorkloadForecastSummary {
		const forecast = this.getForecast(
			days,
			excludeSourceUids,
			includeSourceUids,
			requestRetention,
		);

		if (forecast.length === 0) {
			return {
				avgDaily: 0,
				peakDay: { date: "", count: 0 },
				minDay: { date: "", count: 0 },
				daysAboveTarget: 0,
				needsBalancing: false,
			};
		}

		// Calculate statistics
		let total = 0;
		const empty: WorkloadForecastEntry = {
			date: "",
			dueCount: 0,
			cumulative: 0,
			breakdown: {
				young: 0,
				mature: 0,
				learning: 0,
				projectedRelearning: 0,
			},
		};
		let peakDay = forecast[0] ?? empty;
		let minDay = forecast[0] ?? empty;
		let daysAboveTarget = 0;

		for (const entry of forecast) {
			total += entry.dueCount;

			if (entry.dueCount > peakDay.dueCount) {
				peakDay = entry;
			}
			if (entry.dueCount < minDay.dueCount) {
				minDay = entry;
			}
			if (entry.dueCount > targetPerDay) {
				daysAboveTarget++;
			}
		}

		const avgDaily = total / forecast.length;

		const threshold = targetPerDay * (1 + maxDeviation / 100);
		const needsBalancing = peakDay.dueCount > threshold;

		return {
			avgDaily: Math.round(avgDaily),
			peakDay: { date: peakDay.date, count: peakDay.dueCount },
			minDay: { date: minDay.date, count: minDay.dueCount },
			daysAboveTarget,
			needsBalancing,
		};
	}

	/**
	 * Get cumulative workload (total reviews needed by each date)
	 */
	getCumulativeForecast(
		days: number = 30,
	): { date: string; cumulative: number }[] {
		return this.getForecast(days).map((entry) => ({
			date: entry.date,
			cumulative: entry.cumulative,
		}));
	}

	/**
	 * Get workload by day of week
	 */
	getWorkloadByDayOfWeek(
		days: number = 30,
		excludeSourceUids?: ReadonlySet<string>,
		includeSourceUids?: ReadonlySet<string>,
	): { day: number; dayName: string; avgCount: number }[] {
		const forecast = this.getForecast(
			days,
			excludeSourceUids,
			includeSourceUids,
		);

		// Group by day of week
		const byDay = new Map<number, number[]>();
		for (let i = 0; i < 7; i++) {
			byDay.set(i, []);
		}

		for (const entry of forecast) {
			// entry.date is a date-only string parsed as UTC midnight, so the
			// weekday must be read in UTC — getDay() shifts it west of UTC.
			const dayOfWeek = new Date(entry.date).getUTCDay();
			byDay.get(dayOfWeek)?.push(entry.dueCount);
		}

		const dayNames = [
			"Sunday",
			"Monday",
			"Tuesday",
			"Wednesday",
			"Thursday",
			"Friday",
			"Saturday",
		];

		return Array.from(byDay.entries())
			.map(([day, counts]) => ({
				day,
				dayName: dayNames[day] ?? "Unknown",
				avgCount:
					counts.length > 0
						? Math.round(counts.reduce((a, b) => a + b, 0) / counts.length)
						: 0,
			}))
			.sort((a, b) => a.day - b.day);
	}
}
