-- Database created by True Recall 2.1.0 (9d6ae8e9), schema_version 1.
-- Generated by scripts/snapshot-schema-fixture.ts. Do not edit by hand.
-- FTS5 tables are missing: sql.js cannot create them, and the upgrade
-- code recreates them when it can.
CREATE TABLE note_types (
                id TEXT PRIMARY KEY NOT NULL,
                name TEXT NOT NULL,
                type INTEGER NOT NULL DEFAULT 0,
                fields_json TEXT NOT NULL,
                templates_json TEXT NOT NULL,
                css TEXT DEFAULT '',
                is_builtin INTEGER NOT NULL DEFAULT 0,
                slug TEXT,
                created_at INTEGER,
                updated_at INTEGER,
                deleted_at INTEGER DEFAULT NULL
            );
CREATE TABLE notes (
                id TEXT PRIMARY KEY NOT NULL,
                note_type_id TEXT NOT NULL,
                fields_json TEXT NOT NULL,
                tags TEXT DEFAULT '',
                source_uid TEXT,
                source_text TEXT,
                created_via TEXT DEFAULT 'manual',
                created_at INTEGER,
                updated_at INTEGER,
                deleted_at INTEGER DEFAULT NULL,
                FOREIGN KEY (note_type_id) REFERENCES note_types(id)
            );
CREATE TABLE cards (
                id TEXT PRIMARY KEY NOT NULL,
                note_id TEXT NOT NULL,
                template_ord INTEGER NOT NULL DEFAULT 0,
                due TEXT NOT NULL,
                stability REAL DEFAULT 0,
                difficulty REAL DEFAULT 0,
                reps INTEGER DEFAULT 0,
                lapses INTEGER DEFAULT 0,
                state INTEGER DEFAULT 0,
                last_review TEXT,
                scheduled_days INTEGER DEFAULT 0,
                learning_step INTEGER DEFAULT 0,
                suspended INTEGER DEFAULT 0,
                buried_until TEXT,
                created_at INTEGER,
                updated_at INTEGER,
                deleted_at INTEGER DEFAULT NULL,
                source_uid TEXT,
                FOREIGN KEY (note_id) REFERENCES notes(id)
            );
CREATE TABLE review_log (
                id TEXT PRIMARY KEY NOT NULL,
                card_id TEXT NOT NULL,
                reviewed_at TEXT NOT NULL,
                rating INTEGER NOT NULL,
                scheduled_days INTEGER,
                elapsed_days INTEGER,
                state INTEGER,
                time_spent_ms INTEGER,
                updated_at INTEGER,
                deleted_at INTEGER DEFAULT NULL,
                preset_name TEXT,
                FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE
            );
CREATE TABLE daily_stats (
                date TEXT PRIMARY KEY NOT NULL,
                reviews_completed INTEGER DEFAULT 0,
                new_cards_studied INTEGER DEFAULT 0,
                total_time_ms INTEGER DEFAULT 0,
                again_count INTEGER DEFAULT 0,
                hard_count INTEGER DEFAULT 0,
                good_count INTEGER DEFAULT 0,
                easy_count INTEGER DEFAULT 0,
                new_cards INTEGER DEFAULT 0,
                learning_cards INTEGER DEFAULT 0,
                review_cards INTEGER DEFAULT 0
            );
CREATE TABLE daily_reviewed_cards (
                date TEXT NOT NULL,
                card_id TEXT NOT NULL,
                PRIMARY KEY (date, card_id)
            );
CREATE TABLE assistant_tasks (
                id TEXT PRIMARY KEY NOT NULL,
                thread_id TEXT,
                instruction TEXT NOT NULL,
                preset_id TEXT,
                context_json TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                result_manifest_json TEXT,
                error TEXT,
                created_at INTEGER NOT NULL,
                finished_at INTEGER
            );
CREATE TABLE assistant_threads (
				id TEXT PRIMARY KEY NOT NULL,
				title TEXT NOT NULL,
				context_json TEXT NOT NULL,
				state TEXT NOT NULL DEFAULT 'active',
				messages_json TEXT NOT NULL DEFAULT '[]',
				manifest_json TEXT,
				revisions_json TEXT NOT NULL DEFAULT '[]',
				revision INTEGER NOT NULL DEFAULT 0,
				active_task_id TEXT,
				created_at INTEGER NOT NULL,
				updated_at INTEGER NOT NULL
			);
CREATE TABLE meta (
                key TEXT PRIMARY KEY NOT NULL,
                value TEXT
            );
CREATE INDEX idx_notes_note_type ON notes(note_type_id);
CREATE INDEX idx_notes_source_uid ON notes(source_uid);
CREATE INDEX idx_notes_deleted ON notes(deleted_at);
CREATE INDEX idx_notes_created_via ON notes(created_via);
CREATE INDEX idx_cards_note_id ON cards(note_id);
CREATE INDEX idx_cards_note_template ON cards(note_id, template_ord);
CREATE INDEX idx_cards_due ON cards(due);
CREATE INDEX idx_cards_state ON cards(state);
CREATE INDEX idx_cards_suspended ON cards(suspended);
CREATE INDEX idx_cards_source_uid ON cards(source_uid);
CREATE INDEX idx_cards_deleted ON cards(deleted_at);
CREATE INDEX idx_cards_active ON cards(deleted_at, suspended, state);
CREATE INDEX idx_cards_due_active ON cards(due, deleted_at, suspended);
CREATE INDEX idx_revlog_card ON review_log(card_id);
CREATE INDEX idx_revlog_date ON review_log(reviewed_at);
CREATE INDEX idx_revlog_deleted ON review_log(deleted_at);
CREATE INDEX idx_revlog_card_active ON review_log(card_id, deleted_at);
CREATE INDEX idx_revlog_preset ON review_log(preset_name);
CREATE INDEX idx_revlog_preset_date ON review_log(deleted_at, preset_name, reviewed_at);
CREATE INDEX idx_assistant_tasks_status ON assistant_tasks(status);
CREATE INDEX idx_assistant_threads_state_updated
			ON assistant_threads(state, updated_at DESC);
CREATE INDEX idx_assistant_tasks_thread ON assistant_tasks(thread_id);
INSERT INTO "note_types" ("id", "name", "type", "fields_json", "templates_json", "css", "is_builtin", "slug", "created_at", "updated_at", "deleted_at") VALUES ('builtin-basic', 'Basic', 0, '["Front","Back"]', '[{"name":"Card 1","ordinal":0,"qfmt":"{{Front}}","afmt":"{{Back}}"}]', '', 1, 'basic', 1790440077982, 1790440077982, NULL);
INSERT INTO "note_types" ("id", "name", "type", "fields_json", "templates_json", "css", "is_builtin", "slug", "created_at", "updated_at", "deleted_at") VALUES ('builtin-basic-reversed', 'Basic (reversed)', 0, '["Front","Back"]', '[{"name":"Card 1","ordinal":0,"qfmt":"{{Front}}","afmt":"{{Back}}"},{"name":"Card 2","ordinal":1,"qfmt":"{{Back}}","afmt":"{{Front}}"}]', '', 1, 'basic-reversed', 1790440077982, 1790440077982, NULL);
INSERT INTO "note_types" ("id", "name", "type", "fields_json", "templates_json", "css", "is_builtin", "slug", "created_at", "updated_at", "deleted_at") VALUES ('builtin-cloze', 'Cloze', 1, '["Text","Extra"]', '[{"name":"Cloze","ordinal":0,"qfmt":"{{cloze:Text}}","afmt":"{{cloze:Text}}<br>{{Extra}}"}]', '', 1, 'cloze', 1790440077982, 1790440077982, NULL);
INSERT INTO "note_types" ("id", "name", "type", "fields_json", "templates_json", "css", "is_builtin", "slug", "created_at", "updated_at", "deleted_at") VALUES ('builtin-image-occlusion', 'Image Occlusion', 0, '["Image","Regions"]', '[{"name":"Occlusion","ordinal":0,"qfmt":"{{Image}}","afmt":"{{Image}}{{Regions}}"}]', '', 1, 'image-occlusion', 1790440077982, 1790440077982, NULL);
INSERT INTO "note_types" ("id", "name", "type", "fields_json", "templates_json", "css", "is_builtin", "slug", "created_at", "updated_at", "deleted_at") VALUES ('builtin-note-review', 'Note Review', 0, '["Content"]', '[{"name":"Note Review","ordinal":0,"qfmt":"{{Content}}","afmt":"{{Content}}"}]', '', 1, 'note-review', 1790440077982, 1790440077982, NULL);
INSERT INTO "notes" ("id", "note_type_id", "fields_json", "tags", "source_uid", "source_text", "created_via", "created_at", "updated_at", "deleted_at") VALUES ('fixture-note', 'builtin-basic', '{"Front":"Fixture question","Back":"Fixture answer"}', '', NULL, NULL, 'manual', 1735689600000, 1735689600000, NULL);
INSERT INTO "cards" ("id", "note_id", "template_ord", "due", "stability", "difficulty", "reps", "lapses", "state", "last_review", "scheduled_days", "learning_step", "suspended", "buried_until", "created_at", "updated_at", "deleted_at", "source_uid") VALUES ('fixture-card', 'fixture-note', 0, '2025-01-10T00:00:00.000Z', 4.5, 5.2, 3, 1, 2, '2025-01-05T00:00:00.000Z', 0, 0, 0, NULL, 1735689600000, 1735689600000, NULL, NULL);
INSERT INTO "review_log" ("id", "card_id", "reviewed_at", "rating", "scheduled_days", "elapsed_days", "state", "time_spent_ms", "updated_at", "deleted_at", "preset_name") VALUES ('fixture-review', 'fixture-card', '2025-01-05T00:00:00.000Z', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "meta" ("key", "value") VALUES ('schema_version', '1');
INSERT INTO "meta" ("key", "value") VALUES ('created_at', '2026-09-26 16:27:57');
INSERT INTO "meta" ("key", "value") VALUES ('fts5_available', '0');
