/**
 * Flashcard Parser Service
 * Handles parsing and extracting flashcards from markdown content
 *
 * Supports multi-line questions including code blocks:
 * ```
 * Question text
 * ```typescript
 * code example
 * ``` #flashcard
 * Answer text
 * ```
 */
import { FLASHCARD_CONFIG } from "../../constants";
import { type FlashcardItem } from "../../types";

/**
 * Service for parsing flashcard content from markdown files
 */
export class FlashcardParserService {
	private codeBlockPattern: RegExp = /^\s*(```|~~~)/;
	private tagPattern: RegExp;

	constructor() {
		// Matches any line ending with #flashcard, captures everything before
		this.tagPattern = new RegExp(
			`^(.*)\\s*${FLASHCARD_CONFIG.tag}\\s*$`
		);
	}

	/**
	 * Extract flashcards from content
	 * Parses markdown content and returns all flashcard items with their metadata
	 * Each card gets a new UUID generated by crypto.randomUUID()
	 *
	 * Supports multi-line questions including code blocks.
	 * Questions are accumulated until #flashcard tag is found.
	 * Empty lines (outside code blocks) reset the question accumulation.
	 */
	extractFlashcards(content: string): FlashcardItem[] {
		const flashcards: FlashcardItem[] = [];
		const lines = content.split("\n");

		let questionLines: string[] = [];
		let inQuestionCodeBlock = false;

		for (let i = 0; i < lines.length; i++) {
			const line = lines[i] ?? "";
			const trimmedLine = line.trim();

			// Toggle code block state for question accumulation
			if (this.codeBlockPattern.test(line)) {
				inQuestionCodeBlock = !inQuestionCodeBlock;
			}

			const tagMatch = line.match(this.tagPattern);

			if (tagMatch) {
				// Found #flashcard - finalize question and collect answer
				const beforeTag = tagMatch[1] ?? "";

				// Add the part before #flashcard to question lines
				// (could be empty if #flashcard is on its own line, or contains ``` etc.)
				questionLines.push(beforeTag);

				const question = questionLines.join("\n").trim();
				questionLines = [];
				inQuestionCodeBlock = false;

				if (!question) {
					continue; // Skip if no question content
				}

				// Collect answer
				const answerLines: string[] = [];
				let inAnswerCodeBlock = false;

				i++;
				// Skip leading empty lines between question and answer
				while (i < lines.length && (lines[i] ?? "").trim() === "") {
					i++;
				}

				while (i < lines.length) {
					const answerLine = lines[i] ?? "";

					// Skip legacy ID lines
					if (/^ID:\s*\d+/.test(answerLine)) {
						i++;
						continue;
					}

					// Toggle code block state for answer
					if (this.codeBlockPattern.test(answerLine)) {
						inAnswerCodeBlock = !inAnswerCodeBlock;
					}

					// Check for end of answer:
					// - Empty line outside code block
					// - Next #flashcard tag
					if (
						(answerLine.trim() === "" && !inAnswerCodeBlock) ||
						this.tagPattern.test(answerLine)
					) {
						i--;
						break;
					}

					answerLines.push(answerLine);
					i++;
				}

				const answer = answerLines.join("\n").trim();
				flashcards.push({
					question,
					answer,
					id: crypto.randomUUID(),
				});
			} else if (trimmedLine === "" && !inQuestionCodeBlock) {
				// Empty line outside code block - reset question accumulation
				// This separates unrelated text from flashcard questions
				questionLines = [];
			} else {
				// Accumulate line as potential question content
				questionLines.push(line);
			}
		}

		return flashcards;
	}

	/**
	 * Check if a line is a flashcard question line (contains #flashcard tag)
	 */
	isFlashcardLine(line: string): boolean {
		return this.tagPattern.test(line);
	}

	/**
	 * Get the flashcard tag pattern for external use
	 */
	getFlashcardTag(): string {
		return FLASHCARD_CONFIG.tag;
	}
}
